# Generated by Django 5.1.6 on 2025-02-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_and_authorization', '0003_follow_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
